tasks:
  - init: pip install -r ./requirements.txt
    command : python3 google-serach-lambdatest.py
  - openMode: tab-after
    command: echo -e To see test results goto '\033[4mhttps://automation.lambdatest.com/\033[0m'